Add option to remove quotations marks from returned strings
Scimonster/js-gematriya pull request #1
Opened 2018-12-16 20:10 UTC by peacestone

Changed the API to take an options object instead of a bunch plain parameters.

2019-02-11 14:10 UTC, Scimonster commented
Thanks for the pull request. I like the idea but there are a few changes i'd like made first. I'm commenting on the relevant lines. Basically, please keep it backwards compatible, and ES5 compatible (so no const, no destructuring).

2019-02-11 14:13 UTC, Scimonster requested changes

2019-02-11 14:13 UTC, Scimonster commented on gematriya.js
> +	function gematriya(num, options = {limit: false, punctuate: true, order: false }) {
Parameter defaults are an ES6 feature, please use ES5.

2019-02-11 14:13 UTC, Scimonster commented on gematriya.js
> +		const {limit, punctuate, order} = options;
ES6 destructuring

2019-02-11 14:13 UTC, Scimonster commented on gematriya.js
> +	function gematriya(num, options = {limit: false, punctuate: true, order: false }) {
If this could work in a backwards-compatible manner that would be best.

2019-02-12 17:05 UTC, peacestone commented
I made those changes.

2019-02-14 21:10 UTC, Scimonster approved these changes

2019-02-14 21:10 UTC, merged

2019-02-14 21:10 UTC, Scimonster commented
Thanks!